source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/crspybits/Specs.git'

use_frameworks!

target 'SyncServer_Example' do
	# This is needed because we can't put it in the SyncServer Cocoapod-- it apparently has static frameworks.
	pod 'GoogleSignIn', '4.0.2'
	
	# pod 'SyncServer', :path => '..'
	# pod 'SyncServer/Facebook', :path => '..'
	
	pod 'SyncServer'
	pod 'SyncServer/Facebook'
		
    pod 'SevenSwitch', '~> 2.1'

	target 'SyncServer_Tests' do
    	inherit! :search_paths
  	end
end
