source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/crspybits/Specs.git'

use_frameworks!

target 'SyncServer_Example' do
	pod 'SyncServer'
	pod 'SyncServer/Google'
	pod 'SyncServer/Facebook'
	
    pod 'SevenSwitch', '~> 2.1'

	target 'SyncServer_Tests' do
    	inherit! :search_paths
  	end
end
