source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/crspybits/Specs.git'

use_frameworks!

target 'SyncServer_Example' do
	pod 'SyncServer', :path => '../'
	
	# These two should only be needed right now because I've not pushed the SyncServer pod up to a repo yet.
	# pod 'SMCoreLib', :path => '../../Common/SMCoreLib/'
	pod 'SMCoreLib', '< 1.0'
	pod 'SyncServer-Shared', '< 2.0'
	
    pod 'SevenSwitch', '~> 2.1'
	pod 'Google/SignIn'
	
	pod 'FacebookLogin'
	pod 'FacebookCore'
	
	# 7/29/17. I just added these. Take them out of here eventually. I was just debugging an issue with Xcode9.
	pod 'FBSDKCoreKit', '4.24.0'
	pod 'FBSDKLoginKit', '4.24.0'

	target 'SyncServer_Tests' do
    	inherit! :search_paths
  	end
end
